// Cards Actions //
export const FETCH_CARDS = 'FETCH_CARDS';
export const FETCH_CARDS_FULFILLED = 'FETCH_CARDS_FULFILLED';
export const FETCH_CARDS_REJECTED = 'FETCH_CARDS_REJECTED';
export const LIKE_BTN_CLICKED = 'LIKE_BTN_CLICKED';
export const LIKE_BTN_CLICKED_RECEIVED = 'LIKE_BTN_CLICKED_RECEIVED';
export const LIKE_BTN_CLICKED_REJECTED = 'LIKE_BTN_CLICKED_REJECTED';
export const REMOVE_CARD = 'REMOVE_CARD';
export const REMOVE_CARD_FULFILLED = 'REMOVE_CARD_FULFILLED';
export const REMOVE_CARD_REJECTED = 'REMOVE_CARD_REJECTED';
export const CREATE_CARD = 'CREATE_CARD';
export const CREATE_CARD_FULFILLED = 'CREATE_CARD_FULFILLED';
export const CREATE_CARD_REJECTED = 'CREATE_CARD_REJECTED';
export const TAGLINE_CHANGED = 'TAGLINE_CHANGED';
export const IMGURL_CHANGED = 'IMGURL_CHANGED';

// Users actions //
export const FETCH_USER_ID = 'FETCH_USER_ID';
export const FETCH_USER_ID_FULFILLED = 'FETCH_USER_ID_FULFILLED';
export const FETCH_USER_ID_REJECTED = 'FETCH_USER_ID_REJECTED';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_FULFILLED = 'LOGOUT_FULFILLED';
export const LOGOUT_REJECTED = 'LOGOUT_REJECTED';
export const CHECK_LOGGIN = 'CHECK_LOGGIN';
export const CHECK_LOGGIN_FULFILLED = 'CHECK_LOGGIN_FULFILLED';
export const CHECK_LOGGIN_REJECTED  = 'CHECK_LOGGIN_REJECTED';
